name: AUTO_LOTTERY_FOR_ISEARCH

on:
  # push:
  #   branches:
  #     - master
  workflow_dispatch:
  schedule:
    - cron: '23 8 1-5 * *'
    # cron表达式，Actions时区是UTC时间，比我们所在的时区utf-8晚8个小时
    # 这里我们设置20点0分启动，理论上中国是早上4点0分启动
    # 实测了几次，发现定时任务无法精确到分钟启动，仅能确定实际启动时间比设定时间点晚8个多小时
    
jobs:
  start:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run with Python Script
      env:
        PYTHONUNBUFFERED: 1
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        SERVERPUSHKEY: ${{ secrets.SERVERPUSHKEY }}
        TZ: Asia/Shanghai
      run: |
        python main.py
