name: AUTO_LOTTERY_FOR_ISEARCH

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 10 * * *'
    # cron表达式，Actions时区是UTC时间，所以上午9点要往前推8个小时

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: run with main.py
      env:
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        SERVERPUSHKEY: ${{ secrets.SERVERPUSHKEY }}
        TZ: Asia/Shanghai
      run: |
        python main.py
