name: AUTO_LOTTERY_FOR_ISEARCH

on:
  # push:
  #   branches:
  #     - master
  workflow_dispatch:
  schedule:
    - cron: '30 1 * * *'
    # - cron: '10 0 * * *' 怀疑Github Actions的时间比国内时间相差8小时50分
    # cron表达式，Actions时区是UTC时间，这里是UTC时区每天0点10分运行，即UTF时区每天8点10分
    
jobs:
  start:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run with Python Script
      env:
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        SERVERPUSHKEY: ${{ secrets.SERVERPUSHKEY }}
        TZ: Asia/Shanghai
      run: |
        python main.py
